apiVersion: release-notes/v2
kind: feature
area: installation
releaseNotes:
  - |
    **Added** label `istio.io/exclude-cni=true` node affinity to allow excluding istio-cni from being scheduled on specific nodes.